sudo: required
language: python

matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.7'
  - os: linux
    dist: xenial
    python: '2.7'
  - os: linux
    dist: trusty
    python: '3.4'
  - os: linux
    dist: xenial
    python: '3.4'

before_install:
  - sudo apt-get install git
  - git clone git://github.com/mininet/mininet
  - cd mininet
  - sudo git checkout -b 2.2.2
  - cd ..
  - sudo mininet/util/install.sh -nfv

install:
  - sudo pip install Flask
  - sudo pip install requests
  - sudo mn --version
  - ovs-vsctl --version
  - sudo mn -c

script:
  - sudo python tests/integration.py -v

notifications:
  email: false
    
