sudo: required
language: python

env:
  - distribution: ubuntu
    version: 16.04
    python: 2.7
  - distribution: ubuntu
    version: 14.04
    python: 2.7

before_install:
  - sudo add-apt-repository "deb http://eu-west-2.ec2.archive.ubuntu.com/ubuntu xenial/universe amd64"
  - sudo apt-get update -qq

install:
  - sudo pip install Flask
  - sudo pip install requests
  - sudo apt-get install mininet
  - apt-cache policy mininet
  - sudo mn -c
  - sudo mn --version

script:
  - sudo python tests/integrationPhase3Test.py -v

notifications:
  email: false
    
