language: python
dist: trusty
sudo: required

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq

install:
  - sudo pip install Flask
  - sudo pip install requests
  - sudo apt-get install mininet
  - sudo mn -c
  - sudo mn --version
  - sudo killall ovs-controller

script:
  - sudo python tests/integrationPhase3Test.py -v

notifications:
  email: false
    
