language: python
sudo: required

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo ps aux

install:
  - sudo pip install Flask
  - sudo apt-get install mininet
  - sudo mn -c

script:
  - sudo python tests/integrationPhase3Test.py -v

notifications:
  email:
    on_success: never
