sudo: required
language: python

matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.7'

before_install:
  - echo "{ }" > config.json
  - sudo apt-get update -qq || true
  - sudo apt-get install git
  - git clone git://github.com/mininet/mininet
  - cd mininet
  - sudo git checkout -b 2.2.2
  - cd ..
  - sudo mininet/util/install.sh -nfv

install:
  - sudo pip install Flask
  - sudo pip install requests
  - sudo mn --version
  - sudo mn -c

script:
  - sudo python tests/integrationPhase3Test.py -v

notifications:
  email: false
    
