sudo: required
language: python

env:
  - distribution: ubuntu
    version: 16.04
    python: 2.7
  - distribution: ubuntu
    version: 14.04
    python: 2.7

before_install:
  - echo "{ }" > config.json
  - sudo apt-get update -qq || true
  - sudo apt-get install git
  - git clone git://github.com/mininet/mininet
  - git checkout -b 2.2.1
  - mininet/util/install.sh -nfv

install:
  - sudo pip install Flask
  - sudo pip install requests
  - sudo mn --version
  - sudo mn -c

script:
  - sudo python tests/integrationPhase3Test.py -v

notifications:
  email: false
    
